// Generated by CoffeeScript 1.8.0
(function() {
  var timestamp, today;

  today = 'today';

  console.log('date is', timestamp());

  console.log('today');

  timestamp = function() {
    today = new Date();
    return today;
  };

}).call(this);

//# sourceMappingURL=eshint.js.map
