// Generated by CoffeeScript 1.8.0
(function() {
  var domain, readFile, scenario;

  require("stackup");

  readFile = require("fs").readFile;

  domain = require("domain");

  scenario = function(jsonPath, cb) {
    var d;
    d = domain.create();
    d.on("error", cb);
    d.run(function() {
      readFile(jsonPath, {
        encoding: "utf8"
      }, function(error, contents) {
        cb(error, JSON.parse(contents));
      });
    });
  };

  module.exports = scenario;

}).call(this);

//# sourceMappingURL=mystackup.js.map
