// Generated by CoffeeScript 1.8.0
(function() {
  var bunyan, log, scenario;

  bunyan = require('bunyan');

  log = bunyan.createLogger({
    name: "scenario"
  });

  scenario = function(log, cb) {
    var foo, racer, start, thing, value;
    foo = function() {
      value *= 13;
      log.info({
        value: value
      }, "foo");
      return cb(value);
    };
    racer = function() {
      value &= 255;
      log.info({
        value: value
      }, "racer");
      return setTimeout(foo, 0);
    };
    thing = function() {
      value += 131;
      log.info({
        value: value
      }, "thing");
      return process.nextTick(racer);
    };
    start = function() {
      return process.nextTick(thing);
    };
    value = 97;
    log.info({
      value: value
    }, "scenario");
    start();
    log.error({
      error: "this makes the program incorrect"
    }, "scenario");
    return log.info({
      value: value
    }, "scenario");
  };

  module.exports = scenario;

}).call(this);

//# sourceMappingURL=monitor.js.map
