// Generated by CoffeeScript 1.8.0
(function() {
  var bowser, fs, koopa, peach;

  fs = require("fs");

  peach = function(obj) {
    console.trace('traced');
    return console.dir(obj);
  };

  bowser = function(callback) {
    return fs.readFile(process.argv[2], {
      encoding: "utf8"
    }, callback);
  };

  koopa = function(error, file) {
    if (error != null) {
      console.error(error);
    }
    return peach(JSON.parse(file));
  };

  bowser(koopa);

}).call(this);

//# sourceMappingURL=console.js.map
