// Generated by CoffeeScript 1.8.0
(function() {
  var createServer, server;

  createServer = require('http').createServer;

  server = createServer(function(req, res) {
    return res.end("hello");
  });

  server.listen(9876, function() {
    return console.log("listening");
  });

}).call(this);

//# sourceMappingURL=server.js.map
